### ISSUE TITLE
Source code too big

### ISSUE THREAD

**Issue by jdehaan** [Color-Of-Code/website#527]
Generated source code looks too big and ugly to read (add border to the left and make fonts smaller)

See doc: https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/

**Comment by jdehaan** [comment]
Previous values are 1em and 1.5, I prefer

```css
code[class*="language-"], pre[class*="language-"] {
  font-size: 0.9em;
  line-height: 1.1;
}
```
